defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: true_development

test:
  <<: *defaults
  database: true_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGODB_URI'] %>
  database: true_production
